#!/bin/bash

# This is a basic script that generates a project for me and opens code editor for me to code in.

DIRECTORY="$1"

if [ -d "$DIRECTORY" ];
then
    echo "$DIRECTORY problem implementation already exsists."
    exit
else
    echo "New Problem Initiated, vim open."
fi

cargo new "$DIRECTORY"

curl -s "https://gist.githubusercontent.com/lordofwizard/2cc90c54095ff4835fc93dc9b62eb316/raw/42eae7e8bb4b331f41679b794bb5fa8209ca55ee/Rust%2520Template" > "$DIRECTORY/src/main.rs"

lvim +'14|norm! zz' "$DIRECTORY/src/main.rs"

