#!/bin/bash

# This is a basic script that generates a project for me and opens code editor for me to code in.

DIRECTORY="$1"

if [ -d "$DIRECTORY" ];
then
    echo "$DIRECTORY problem implementation already exsists."
    exit
else
    echo "New Problem Initiated, vim open."
fi

cargo new "$DIRECTORY"

curl -s "https://raw.githubusercontent.com/lordofwizard/script/main/main.rs" > "$DIRECTORY/src/main.rs"
#cat ~/code/bash/script/main.rs > "$DIRECTORY/src/main.rs"
#lvim +'14|norm! zz' "$DIRECTORY/src/main.rs"
#tmux new -s foo '~/.local/bin/lvim +"14|norm! zz" {"$DIRECTORY/src/main.rs"} ; $SHELL'
#tmux new -s foo "~/.local/bin/lvim +'14|norm! zz' '$DIRECTORY/src/main.rs' ; $SHELL"
tmux new-session -s prog "~/.local/bin/lvim +'14|norm! zz' '$DIRECTORY/src/main.rs'"
