#!/bin/sh
echo -e "Type the name for your new competitive programming project"
printf "Name -: "
read PROJ_FOLDER

mkdir -p $PROJ_FOLDER
cd $PROJ_FOLDER
curl -s https://raw.githubusercontent.com/lordofwizard/script/main/code.cpp > code.cpp
